spring:
  datasource:
    url: YOUR_URL
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: <Login User to SMTP server>
    password: <Login password to SMTP server>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    token:
      secret-key: secret
      expire-length: 3600000

aws:
  region: your_region
  accessKey: your_key
  secretAccessKey: your_secret_key
